POST http://localhost:8081/api/todo
Content-Type: application/json

{
    "task": "Task 4"
}

###

PATCH http://localhost:8081/api/todo/64648f66cddf7376de2cf948
Content-Type: application/json

{
    "task": "Task Modified",
    "completed": true
}

###

DELETE http://localhost:8081/api/todo/64647cac5e903b9eed0e1466